version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minh-nhut-nestjs-app
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/nestjs-db
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
